src/objects/Case_Swarm_Rule__c.object
<CustomObject>
    <description>Chatterで、ケースを自動フォローさせる公開グループのルールを示す。</description>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>ケース種別</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Id__c</fullName>
        <label>公開グループID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>タイプ</label>
        <picklist>
            <picklistValues>
                <fullName>全てのケース</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>自分が所有しているケース</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>指定する状況のケース</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>指定する優先度のケース</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>指定する種別のケース</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>ケース自動フォロールール</label>
    <nameField>
        <displayFormat>CSR-{0000}</displayFormat>
        <label>ケース自動フォロールールID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ケース自動フォロールール</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity_Swarm_Rule__c.object
<CustomObject>
    <description>Chatterで、商談を自動フォローさせる公開グループのルールを示す。</description>
    <fields>
        <fullName>Group_Id__c</fullName>
        <label>公開グループID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>タイプ</label>
        <picklist>
            <picklistValues>
                <fullName>全ての商談</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>自分が所有している商談</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>指定する金額以上の商談</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>指定するフェーズの商談</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>指定する種別の商談</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>商談自動フォロールール</label>
    <nameField>
        <displayFormat>OSR-{0000}</displayFormat>
        <label>商談自動フォロールールID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>商談自動フォロールール</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SwarmTriggerTests.cls
@isTest
private class SwarmTriggerTests {

    static testMethod void testGroups() {
        User user1 = SwarmTestUtility.createTestUser();
        Group group1 = SwarmTestUtility.createGroup('Group'+SwarmTestUtility.createRandomWord());
        SwarmTestUtility.joinGroup(user1, group1);
        
        System.runAs(user1) {
        Case_Swarm_Rule__c csr = new Case_Swarm_Rule__c();
        csr.Case_Type__c = 'One';
        
        //fails when it's not an ID
        csr.Group_Id__c = 'Fail';
        
        try {
        	insert csr;
        	System.assert(False);
        } catch (Exception e) {
        	
        }
        
        //fails when it's a bad ID
        csr.Group_Id__c = 'a00A0000001tXne';
        
        try {
        	insert csr;
        	System.assert(False);
        } catch (Exception e) {
        	
        }   
        
        //succeed when it's a good if
        csr.Group_Id__c = group1.Id;
        
    	insert csr;
        
        //
        Opportunity_Swarm_Rule__c osr = new Opportunity_Swarm_Rule__c();
        osr.Type__c = 'One';
        
        //fails when it's not an ID
        osr.Group_Id__c = 'Fail';
        
        try {
        	insert osr;
        	System.assert(False);
        } catch (Exception e) {
        	
        }
        
        //fails when it's a bad ID
        osr.Group_Id__c = 'a00A0000001tXne';
        
        try {
        	insert osr;
        	System.assert(False);
        } catch (Exception e) {
        	
        }   
        
        //succeed when it's a good if
        osr.Group_Id__c = group1.Id;
        
    	insert osr;
        }
        
    }
}