src/objects/LoginAccount__c.object
<CustomObject>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>User Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Login Account</label>
    <nameField>
        <label>Login Account Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LoginAccountManagerConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>ConsumerKey__c</fullName>
        <label>Consumer Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConsumerSecret__c</fullName>
        <label>Consumer Secret</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Login Account Manager Config</label>
</CustomObject>

src/classes/LoginAccountCheckControllerTest.cls
@isTest
private class LoginAccountCheckControllerTest {
    static LoginAccount__c init(String username) {
        LoginAccountManagerConfig__c config = new LoginAccountManagerConfig__c(
            Name = 'Core',
            ConsumerKey__c = 'test',
            ConsumerSecret__c = 'test'
        );
        insert config;

        LoginAccount__c la = new LoginAccount__c(
            Name = 'test',
            UserName__c = username,
            Password__c = 'test'
        );
        insert la;
        return la;
    }

    static testMethod void test1Test() {
        LoginAccount__c la = init('test1@test.com');

        Test.startTest();
        LoginAccountCheckControllerTester tester = new LoginAccountCheckControllerTester(
            new ApexPages.StandardController([Select Id, UserName__c From LoginAccount__c Where Id = :la.Id])
        );
        tester.updateData();
        Test.stopTest();
    }

    static testMethod void test2Test() {
        LoginAccount__c la = init('test2@test.com');

        Test.startTest();
        LoginAccountCheckControllerTester tester = new LoginAccountCheckControllerTester(
            new ApexPages.StandardController([Select Id, UserName__c From LoginAccount__c Where Id = :la.Id])
        );
        tester.updateData();
        Test.stopTest();
    }

    static testMethod void errorTest() {
        LoginAccount__c la = init('error@test.com');

        Test.startTest();
        LoginAccountCheckControllerTester tester = new LoginAccountCheckControllerTester(
            new ApexPages.StandardController([Select Id, UserName__c From LoginAccount__c Where Id = :la.Id])
        );
        tester.updateData();
        Test.stopTest();
    }

	static testMethod void cronTest() {
        LoginAccount__c la = init('test1@test.com');

        Test.startTest();
        LoginAccountManagerCron t = new LoginAccountManagerCron();
        t.start();
        t.execute(NULL);
        t.deleteAll();
    }
}